[package]
name = "thrutch"
version = "1.3.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "^0.8"
dirs = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = {version = "2", features = ["yaml"]}
